name: Generate Doxygen documentation and deploy to pages

on:
  push:
  repository_dispatch:
    types: [global-update]

jobs:
  docs:
    permissions:
      pages: write
      id-token: write
    uses: ft-spellbook/mock-global/.github/workflows/test.yml@master
    with:
      name: "libft"
      brief: "tgrekov School42 libft 2023"